project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from Placowki import views
from Profile.views import *
from Personel.views import *
from Pacjent.views import *
from Placowki.views import *
from Terminarz.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Logowanie i Rejestracja APK Profile
    path('registration', registration, name='registration'),
    path('', loginPage, name='loginPage'),
    path('logout/', logoutUser, name='logout'),

    #Panel Admina django
    path('admin/', admin.site.urls, name='admin'),
        # Admin panel
    path('home/', home,name='home' ),
    path('home/users/<int:pk>', user_person,name='user_person' ),
    path('home/register', orga_admin ,name='orga_admin' ),
    path('home/register/orga_tabs', orga_admin_tabs ,name='orga_admin_tabs' ),
    path('home/register/struct', struct_admin ,name='struct' ),
    path('home/register/unit', unit_admin ,name='unit' ),
    path('home/register/orga_tabs/one/<int:pk>', orga_admin_tabs_one ,name='orga_admin_tabs_one' ),
    path('home/register/orga_tabs/unit/<int:pk>', orga_admin_one_unit ,name='orga_admin_one_unit' ),
    path('home/register/unit/<int:pk>', admin_one_unit  ,name='admin_one_unit' ),
    path('home/register/orga_tabs/delete/<int:pk>', delete_organization ,name='delete_organization' ),
    path('home/register/orga_tabs/one/delete/<int:dd>/<int:pi>', delete_struct ,name='delete_struct' ),
    path('home/register/orga_tabs/one/unit/delete/<int:dd>/<int:pi>', delete_unit ,name='delete_unit' ),
    # path('home/register/orga_tabs/<int:pk>', orga_admin_tabs ,name='orga_admin_tabs_edit' ),
    path('person/', user_web,name='user_web' ),#Rejestr personelu
    path('users/', users_web,name='users_web' ),
    path('users/adduser', adduser ,name='adduser' ),
    path('users/adduser/person/<int:pk>', adduserPerson ,name='adduserPER' ),
    path('deleteper/<int:pk>', delete_per ,name='delete_per' ),
    path('deleteusers/<int:pk>/<int:pi>/', deleteusers ,name='deleteusers' ),
    path('edituser/<int:pk>/', infouser ,name='infouser' ),
    path('document_page_adm/', document_upload_adm, name="upload_adm"),
    path('termgeneric/', term_gen, name='term_gen' ),
    # path('visit_adm/', register_visit_adm, name='visit_adm'),



    # Personel panel
    path('home2/', home_per,name='home_per' ),
    path('home2/dekl', deklPERS ,name='deklPERS' ),
    path('home2/deklaracje', showdekl ,name='showdekl' ),
    path('home2/dekl/<int:pk>', deklPERSone ,name='deklPERSone' ),
    path('home2/form/<int:pk>', formsPERS ,name='formsPERS' ),
    path('home2/doc/<int:pk>', docPERS ,name='docPERS' ),
    path('home2/dekl/<int:pk>/<int:pi>', deklREJ ,name='deklREJ' ),
    path('home2/deklone/<int:pk>/', deklREJlek ,name='deklREJlek' ),
    path('home/form_all/', add_form ,name='add_form' ),
    path('home/doc_all/', doc_show ,name='doc_show' ),
    path('check/', check_per ,name='check_per' ),
    path('editper/', editper ,name='editper' ),
    path('check/<int:pk>', check ,name='check' ),
    path('delete_user/<int:pk>', deleteuser, name="deleteuser"),
    path('visit_check/', visit_per, name='visit_per'),
    path('visit_check/one/<int:pk>', visit_one, name='visit_one_PERS'),
    path('visit_check/place', place, name='place'),
    path('visit_check/place/<int:pk>', lekvis, name='lekvis'),
    path('visit_check/place/<int:pk>/<int:pi>', regvis, name='regvis'),

    #Panel lekarza
    path('homelek/', home_lek, name='home_lek'),
    path('homelek/place/', placeform, name='placeform'),
    path('homelek/place/<int:pk>', showvisit, name='showvisit'),
    path('homelek/place/visit/<int:pk>', editvisit, name='editvisit'),
    path('homelek/profile', editlek, name='editlek'),

    # PACJENT PANEL
    path('home1/', home_user,name='home_user' ),
    path('notcheck/', not_check,name='not_check' ),
    path('document_page/', document_upload, name="upload"),
    path('delete_doc/<int:id>', deleteItem, name="deleteItem"),
    path('editprofile/', Edit_form, name='editprofile'),
    path('visit/', register_visit, name='visit'),
    path('visitone/<int:pk>', ONE_visit, name='visit_one'),
    path('cancel/<int:pk>', cancel, name='cancel'),
    path('visitregi/<int:pk>/<int:pi>', visit_register, name='visit_register'),
    path('systemrec/', e_systemREC, name='e_systemREC'),
    path('systemskier/', e_systemSKIER, name='e_systemSKIER'),
    path('organization/', organizations, name='organization'),
    path('organization/spec', spec , name='spec'),
    path('organization/hospital', hospital , name='hospital'),
    path('organization/clinic', clinic , name='clinic'),
    path('organization/page/<int:id>', organizations_page, name='organization_page'),
    path('organization/<int:id>', organizations_next, name='organization_next'),
    # path('registervisit/', register_visit, name='register_visit'),
    path('visitreg/<int:unitpk>/<int:perspk>', visitreg, name='visitreg'),
    path('dekl', DEKL_ON, name='dekl'),


    path('api-auth/', include('rest_framework.urls')),


    # url(r'^test/$', views.test.as_view(), name='test-list'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Pacjent/models.py
from django.db import models
from django.contrib.auth.models import *
from Placowki.models import *
from Profile.models import *
from Terminarz.models import *
from Slowniki.models import *
# Create your models here.


class Document(models.Model):
    name = models.CharField("Nazwa", max_length=100, null=True, unique=True)
    author_user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, verbose_name="Użytkownik")
    author_person = models.ForeignKey(Personal, on_delete=models.PROTECT, null=True, verbose_name="Pacjent")
    doc = models.FileField("Załącznik", null=True, blank=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Dokumenty"

class Visit(models.Model):
    STATUS = (
        ('0', ('Niepotwierdzony')),
        ('1', ('Potwierdzony')),

    )
    STATUS_AC = (
        ('0', ('Zarejestrowana')),
        ('1', ('Zapalnowana')),
        ('2', ('Do realizacji')),
        ('3', ('Zrealizowana')),
        ('4', ('Odwołana')),

    )
    VISIT_TYPE = (
        ('0', ('Receptowa')),
        ('1', ('Porada')),
        ('2', ('Teleporada')),
        ('3', ('Z skierowaniem')),
        ('4', ('Kontynuacja')),
        ('5', ('')),


    )
    patient_user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    patient_person = models.ForeignKey(Personal, on_delete=models.PROTECT, null=True)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, null=True, verbose_name="Komórka Organizacyjna")
    struct = models.ForeignKey(Struct_Organization, on_delete=models.PROTECT, null=True, verbose_name="Zakład leczniczy")
    unity = models.ForeignKey(Unit, on_delete=models.PROTECT, null=True, verbose_name="Jednostka ")
    term = models.ForeignKey(Term_day, on_delete=models.CASCADE, unique=True, null=True, verbose_name="Data Wizyty ")
    key = models.CharField("Kod e-skierowania", max_length=4, null=True)
    id10 = models.ManyToManyField(ICD10, verbose_name="Rozpoznania", null=True)
    description = models.TextField("Opis", null=True)
    description_person = models.TextField("Opis lekarza", null=True)
    status = models.CharField("Status aktualny", max_length=100, null=True, choices=STATUS_AC, default='0')
    confirmation = models.CharField("Potwierdzenie wizyty", max_length=100,
                                    choices=STATUS, default='0', null=True)
    type_visit = models.CharField("Rodzajy Wizyty", max_length=100,
                                    choices=VISIT_TYPE, default='5')
    dateregister = models.DateField(default=timezone.now)




    class Meta:
        verbose_name_plural = "Wizyty"

class e_system_SKIEROWANIA(models.Model):
    key_e = models.CharField("Kod skierowania", max_length=4, null=True, blank=True, unique=True)
    idvisit = models.ForeignKey(Visit, on_delete=models.PROTECT, verbose_name="Wizyta")
    idpac = models.ForeignKey(Personal, on_delete=models.PROTECT, verbose_name="Pacjents")
    iddoc = models.ForeignKey(Personal_med, on_delete=models.PROTECT, verbose_name="Lekarz")

    def __str__(self):
        return (self.key_e)

    class Meta:
        verbose_name_plural = "Skierowania"
class e_system_RECEPTY(models.Model):
    key_e = models.CharField("Kod Recepty", max_length=4, null=True, blank=True, unique=True)
    idvisit = models.ForeignKey(Visit, on_delete=models.PROTECT, verbose_name="Wizyta")
    idpac = models.ForeignKey(Personal, on_delete=models.PROTECT, verbose_name="Pacjents")
    iddoc = models.ForeignKey(Personal_med, on_delete=models.PROTECT, verbose_name="Lekarz")

    def __str__(self):
        return (self.key_e)

    class Meta:
        verbose_name_plural = "Recepty"

class Form_all(models.Model):

     name = models.CharField("Nazwa Formularza do pobrania", max_length=100, null=True, blank=True)
     file = models.FileField("Fromularz do pobrania", null=True, blank=True)

     def __str__(self):
         return (self.name)
     class Meta:
         verbose_name_plural = "Formularze"


class Form_user(models.Model):

    FORM_TYPE = (
        ('0', ('Deklaracja do Lekarza')),
        ('1', ('Deklaracja do Pielęgniarki środowiskowej')),
        ('2', ('Deklaracja do Położnej')),
        ('3', ('Formularz zdrowotny COVID')),
    )
    STAUS = (
        ('0', ('Przesłany')),
        ('1', ('W trakcie weryfikacji')),
        ('2', ('Zakceptowany')),
        ('3', ('Niezakceptowany')),

    )
    name = models.CharField("Nazwa przesłanego Formularza ", max_length=100, null=True, blank=True)
    patient_person = models.ForeignKey(Personal, on_delete=models.PROTECT, null=True, verbose_name="Pacjent")
    # medical = models.ForeignKey(Personal_med, on_delete=models.PROTECT, null=True, verbose_name="Personel")
    type_forms = models.CharField("Rodzaj Formularza", max_length=100, null=True, choices=FORM_TYPE)
    status = models.CharField("Status dokumentu", max_length=100, null=True, choices=STAUS, default=0)
    remarks_user = models.TextField("Uwagi użytkownika", null=True)
    remarks_person = models.TextField("Uwagi Pracownika placówki", null=True)
    name_unit = models.ForeignKey(Unit, on_delete=models.PROTECT, verbose_name="Jednostka", null=True)
    publish_date = models.DateField("Data przesłania", default=timezone.now)
    file = models.FileField("Fromularz do pobrania", null=True, blank=True)

    def __str__(self):
        return (self.name)
    class Meta:
        verbose_name_plural = "Formularze przesłane przez użytkownika"
class dekl(models.Model):

    idpac = models.ForeignKey(Personal, on_delete=models.CASCADE, unique=True, null=True, verbose_name="Pacjent")
    iddoc = models.ForeignKey(Personal_med, on_delete=models.CASCADE, unique=True, null=True, verbose_name="Lekarz")
    idunit = models.ForeignKey(Unit, on_delete=models.CASCADE, verbose_name="Jednostka")
    idfield = models.ForeignKey(Form_user, on_delete=models.CASCADE, unique=True, null=True, verbose_name="Formularz")

    class Meta:
        verbose_name_plural = "Deklaracje"

Terminarz/models.py
from django.db import models
from Placowki.models import *
from Profile.models import *
from django.utils import timezone, dateformat
# Create your models here.
class Term(models.Model):
    WORK = (
        ('0', ('Lekarz')),
        ('1', ('Pielęgniarka')),
        ('2', ('Położna')),
    )
    DAY = (
        (0, ('Poniedziałek')),
        (1, ('Wtorek')),
        (2, ('Środa')),
        (3, ('Czwartek')),
        (4, ('Piątek')),
        (5, ('Sobota')),
        (6, ('Niedziela')),
    )

    work_place = models.ForeignKey(Unit, on_delete=models.PROTECT, null=True, verbose_name="Jednostka")
    work_person = models.ForeignKey(Personal_med, on_delete=models.PROTECT, null=True, verbose_name="Osoba personelu")
    work_type = models.CharField("Typ terminarza", max_length=100, choices=WORK, null=True)
    work_start = models.TimeField(auto_now=False, auto_now_add=False, verbose_name="Początek wizyty")
    work_stop = models.TimeField(auto_now=False, auto_now_add=False, verbose_name="Koniec wizyty")
    work_day = models.IntegerField("Dzień tygodnia", null=True, choices=DAY)
    work_time = models.IntegerField("Czas trwania wizyty", null=True)
    work_start_date = models.DateField("Data początku",null=True)
    work_stop_date = models.DateField("Data początku",null=True)
    work_date = models.DateField("Data generacji", default=timezone.now , null=True)
    class Meta:
        verbose_name_plural = "Harmonogram"

class Term_day(models.Model):
    DAY = (
        ('0', ('Poniedziałek')),
        ('1', ('Wtorek')),
        ('2', ('Środa')),
        ('3', ('Czwartek')),
        ('4', ('Piątek')),
        ('5', ('Sobota')),
        ('6', ('Niedziela')),
    )
    work_place = models.ForeignKey(Unit, on_delete=models.PROTECT, null=True, verbose_name="Jednostka")
    work_person = models.ForeignKey(Personal_med, on_delete=models.PROTECT, null=True, verbose_name="Osoba personelu")
    work_date = models.DateField("Data", null=True)
    work_time = models.TimeField(auto_now=False, auto_now_add=False, verbose_name="Godzina wizyty")
    work_day = models.CharField("Dzień tygodnia", max_length=100, null=True, choices=DAY)
    work_type = models.CharField("Typ terminarza", max_length=100, null=True)


    def __str__(self):

        text_date = self.work_date.strftime("%m/%d/%Y")
        text_time = self.work_time.strftime("%H:%M:%S")
        return (text_date +' '+ text_time)

    class Meta:
        verbose_name_plural = "Terminarz"

Pacjent/forms.py
from django import forms
from django.contrib.auth.models import User
from Pacjent.models import *
from Slowniki.models import *



class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('name', 'doc')

class VisitForm_CUST(forms.ModelForm):

    patient_user = forms.ModelChoiceField( queryset = User.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), label="Użytkownik")
    patient_person = forms.ModelChoiceField(queryset= Personal.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), label="Pesel")
    unity = forms.ModelChoiceField( queryset=Unit.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), label="Jednostka lecznicza")
    struct = forms.ModelChoiceField( queryset=Struct_Organization.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), label="Zakład leczniczy")
    organization = forms.ModelChoiceField(queryset=Organization.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), label="Podmiot leczniczy")
    key = forms.CharField(widget=forms.NumberInput(attrs={"class": "form-control"}), label="Kod e-skierowania")

    description = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "placeholder": "Opisz w jakim celu rejestrujesz się do lekarza"}), label="OPIS")


    class Meta:
        model = Visit
        fields= ( 'patient_user' ,'patient_person', 'organization', 'struct','unity', 'description', 'key' )

class VisitForm_EDIT_PAC(forms.ModelForm):

    class Meta:
        model = Visit
        fields= ( 'term', )
    def __init__(self, unitpk, personid, *args, **kwargs):
        super(VisitForm_EDIT_PAC, self).__init__(*args, **kwargs)

        self.fields['term'].queryset = Term_day.objects.filter(work_place=unitpk, work_person=personid)

class DEKLFORM(forms.ModelForm):
    FORM_TYPE = (
        ('0', ('Deklaracja do Lekarza')),
    )
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}), label="Nazwa formularza")
    type_forms = forms.ChoiceField(widget=forms.Select(attrs={"class": "form-control"}), choices=FORM_TYPE ,label="Typ formularza")
    remarks_user = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}), label="Opis pacjenta")
    file = forms.FileField(widget=forms.FileInput(attrs={"class": "form-control"}), label="Formularz")
    class Meta:
        model = Form_user
        fields = ('name',  'type_forms', 'remarks_user', 'file' )

templates/Worker/Visit_person.html
{% extends "Worker/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block style %}
        <link rel="stylesheet" href="{% static 'style/style02.css' %}">

{% endblock %}
{% block navbar %}


                <div class="nav_list"> <a href="{% url 'showdekl' %}" class="nav_link "> <i class='bx bx-grid-alt nav_icon'></i> <span class="nav_name">Deklaracje</span> </a>
                    <a href="{% url 'add_form' %}" class="nav_link"> <i class='bx bxs-file-plus nav_icon'></i> <span class="nav_name">Dodaj formularz</span> </a>
                    <a href="{% url 'deklPERS' %}" class="nav_link"> <i class='bx bxs-file-pdf nav_icon' ></i> <span class="nav_name">Formularze</span> </a>
                    <a href="{% url 'doc_show' %}" class="nav_link"> <i class='bx bxs-file-doc nav_icon' ></i> <span class="nav_name">Dokumenty</span> </a>
                    <a href="{% url 'visit_per' %}" class="nav_link active"> <i class='bx bx-table nav_icon'></i> <span class="nav_name">Rejestr wizyt</span> </a>
                    <a href="{% url 'editper' %}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Profil</span> </a>
                    </div>
{% endblock navbar %}
{% block content %}
    <br/>
    <br/>
    <br/>
{{ forms.erorrs }}
<form method="post">
{%  csrf_token  %}


{#{{ forms.name}}#}
<select class="select form-control" name="name" id="id_name">
    <option value selected>Wybierz Lekarza</option>
    {% for x in show %}

        {% if x.name.groupadd.id == 3 %}
        <option value="{{ x.name.id}}">{{ x.name }}   </option>
        {% endif %}
{% endfor %}
</select>
<input type="submit" name="two" class="btn btn-primary" value="Wybierz">
</form>















{% endblock content %}
{% block extrascripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>
{#    <script type="text/javascript">#}
{#      $(document).ready(function () {#}
{#      $('select').selectize({#}
{#          sortField: 'text'#}
{#      });#}
{#  });#}
{#    </script>#}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>

    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}

templates/Worker/dekl.html
{% extends "Worker/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block style %}
        <link rel="stylesheet" href="{% static 'style/style02.css' %}">

{% endblock %}
{% block navbar %}


              <div class="nav_list"> <a href="{% url 'showdekl' %}" class="nav_link "> <i class='bx bx-grid-alt nav_icon'></i> <span class="nav_name">Deklaracje</span> </a>
                    <a href="{% url 'add_form' %}" class="nav_link"> <i class='bx bxs-file-plus nav_icon'></i> <span class="nav_name">Dodaj formularz</span> </a>
                    <a href="{% url 'deklPERS' %}" class="nav_link active"> <i class='bx bxs-file-pdf nav_icon' ></i> <span class="nav_name">Formularze</span> </a>
                    <a href="{% url 'doc_show' %}" class="nav_link"> <i class='bx bxs-file-doc nav_icon' ></i> <span class="nav_name">Dokumenty</span> </a>
                    <a href="{% url 'visit_per' %}" class="nav_link"> <i class='bx bx-table nav_icon'></i> <span class="nav_name">Rejestr wizyt</span> </a>
                    <a href="{% url 'editper' %}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Profil</span> </a>
                    </div>
{% endblock navbar %}
{% block content %}

    <div class="container">

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    </div>


    <h1 style="text-align: center"> Deklaracje</h1>
{% for message in messages %}
                <h3 id="message">{{ message }}</h3>

            {% endfor %}



    <div  class="col">

    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="table-responsive">
                    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                                    <thead>
                                        <tr role="row">

                                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 20.641px;">#</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 160.312px;">Nazwa</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 160.312px;">Typ formularza</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Pacjent</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Status dokumentu</th>
                                        </tr>
                                    </thead>
                                    <tbody>



                                         {% for x in show %}
                                            <tr role="row" class="odd">

                                                <td class="sorting_1">{{ forloop.counter }}</td>
                                                <td><div class="d-grid gap-2">    <a type="button" href="{% url 'deklPERSone' pk=x.id %}" class="btn btn-outline-primary"  ><b>{{ x.name }} </b>Szczegóły</a></div></td>
                                                <td> {{ x.get_type_forms_display }}</td>
                                                <td> {{ x.patient_person.first_name }} {{ x.patient_person.last_name }} <br/>{{ x.patient_person.pesel }}</td>
                                                <td>{{ x.publish_date }}<br/>{{ x.get_status_display }} </td>





                                            </tr>
                                               {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock content %}
{% block extrascripts %}

    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>

    <script type="text/javascript">$('#sampleTable').DataTable();</script>

{% endblock extrascripts %}

templates/Worker/deklrejlek.html
{% extends "Worker/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block style %}
        <link rel="stylesheet" href="{% static 'style/style02.css' %}">

{% endblock %}
{% block navbar %}


              <div class="nav_list"> <a href="{% url 'showdekl' %}" class="nav_link active "> <i class='bx bx-grid-alt nav_icon'></i> <span class="nav_name">Deklaracje</span> </a>
                    <a href="{% url 'add_form' %}" class="nav_link"> <i class='bx bxs-file-plus nav_icon'></i> <span class="nav_name">Dodaj formularz</span> </a>
                    <a href="{% url 'deklPERS' %}" class="nav_link"> <i class='bx bxs-file-pdf nav_icon' ></i> <span class="nav_name">Formularze</span> </a>
                    <a href="{% url 'doc_show' %}" class="nav_link"> <i class='bx bxs-file-doc nav_icon' ></i> <span class="nav_name">Dokumenty</span> </a>
                    <a href="{% url 'visit_per' %}" class="nav_link"> <i class='bx bx-table nav_icon'></i> <span class="nav_name">Rejestr wizyt</span> </a>
                    <a href="{% url 'editper' %}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Profil</span> </a>
                    </div>
{% endblock navbar %}
{% block content %}



    <h1 style="text-align: center; padding-top: 35px;"> Uzupełnianie deklaracji pacjenta {{ show.idpac.first_name }} {{ show.idpac.last_name }}</h1>
    <h3 style="text-align: center">Numer deklaracji {{ show.id }}<br/> Do jednostki {{ show.idunit.name }} w zakładzie leczniczym {{ show.idunit.organization.name }}</h3>
{% for message in messages %}
                <h3 id="message">{{ message }}</h3>

            {% endfor %}

<form method="post">
{% csrf_token %}


    <select name="iddoc" class="form-select" id="id_iddoc" aria-label="Default select example">
    <option selected>Wybierz lekarza...</option>
        {% for x in place %}

  <option value="{{ x.name.id }}">{{ x.name }}</option>
    {% endfor %}
</select>

<br/>
<input type="submit" class="btn btn-info" value="Dodaj lekarza">
</form>




{% endblock content %}
{% block extrascripts %}

    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>

    <script type="text/javascript">$('#sampleTable').DataTable();</script>

{% endblock extrascripts %}