project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from Placowki import views
from Profile.views import *
from Personel.views import *
from Pacjent.views import *
from Placowki.views import *
from Terminarz.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Logowanie i Rejestracja APK Profile
    path('registration', registration, name='registration'),
    path('', loginPage, name='loginPage'),
    path('logout/', logoutUser, name='logout'),

    #Panel Admina django
    path('admin/', admin.site.urls, name='admin'),
        # Admin panel
    path('home/', home,name='home' ),
    path('home/users/<int:pk>', user_person,name='user_person' ),
    path('home/register', orga_admin ,name='orga_admin' ),
    path('home/register/orga_tabs', orga_admin_tabs ,name='orga_admin_tabs' ),
    path('home/register/struct', struct_admin ,name='struct' ),
    path('home/register/unit', unit_admin ,name='unit' ),
    path('home/register/orga_tabs/one/<int:pk>', orga_admin_tabs_one ,name='orga_admin_tabs_one' ),
    path('home/register/orga_tabs/unit/<int:pk>', orga_admin_one_unit ,name='orga_admin_one_unit' ),
    path('home/register/unit/<int:pk>', admin_one_unit  ,name='admin_one_unit' ),
    path('home/register/orga_tabs/delete/<int:pk>', delete_organization ,name='delete_organization' ),
    path('home/register/orga_tabs/one/delete/<int:dd>/<int:pi>', delete_struct ,name='delete_struct' ),
    path('home/register/orga_tabs/one/unit/delete/<int:dd>/<int:pi>', delete_unit ,name='delete_unit' ),
    # path('home/register/orga_tabs/<int:pk>', orga_admin_tabs ,name='orga_admin_tabs_edit' ),
    path('person/', user_web,name='user_web' ),#Rejestr personelu
    path('users/', users_web,name='users_web' ),
    path('users/adduser', adduser ,name='adduser' ),
    path('users/adduser/person/<int:pk>', adduserPerson ,name='adduserPER' ),
    path('deleteper/<int:pk>', delete_per ,name='delete_per' ),
    path('deleteusers/<int:pk>/<int:pi>/', deleteusers ,name='deleteusers' ),
    path('edituser/<int:pk>/', infouser ,name='infouser' ),
    path('document_page_adm/', document_upload_adm, name="upload_adm"),
    path('termgeneric/', term_gen, name='term_gen' ),
    # path('visit_adm/', register_visit_adm, name='visit_adm'),



    # Personel panel
    path('home2/', home_per,name='home_per' ),
    path('home2/dekl', deklPERS ,name='deklPERS' ),
    path('home2/deklaracje', showdekl ,name='showdekl' ),
    path('home2/dekl/<int:pk>', deklPERSone ,name='deklPERSone' ),
    path('home2/form/<int:pk>', formsPERS ,name='formsPERS' ),
    path('home2/doc/<int:pk>', docPERS ,name='docPERS' ),
    path('home2/dekl/<int:pk>/<int:pi>', deklREJ ,name='deklREJ' ),
    path('home2/deklone/<int:pk>/', deklREJlek ,name='deklREJlek' ),
    path('home/form_all/', add_form ,name='add_form' ),
    path('home/doc_all/', doc_show ,name='doc_show' ),
    path('check/', check_per ,name='check_per' ),
    path('editper/', editper ,name='editper' ),
    path('check/<int:pk>', check ,name='check' ),
    path('delete_user/<int:pk>', deleteuser, name="deleteuser"),
    path('visit_check/', visit_per, name='visit_per'),
    path('visit_check/one/<int:pk>', visit_one, name='visit_one_PERS'),
    path('visit_check/place', place, name='place'),
    path('visit_check/place/<int:pk>', lekvis, name='lekvis'),
    path('visit_check/place/<int:pk>/<int:pi>', regvis, name='regvis'),

    #Panel lekarza
    path('homelek/', home_lek, name='home_lek'),
    path('homelek/place/', placeform, name='placeform'),
    path('homelek/place/<int:pk>', showvisit, name='showvisit'),
    path('homelek/place/visit/<int:pk>', editvisit, name='editvisit'),
    path('homelek/profile', editlek, name='editlek'),

    # PACJENT PANEL
    path('home1/', home_user,name='home_user' ),
    path('notcheck/', not_check,name='not_check' ),
    path('document_page/', document_upload, name="upload"),
    path('delete_doc/<int:id>', deleteItem, name="deleteItem"),
    path('editprofile/', Edit_form, name='editprofile'),
    path('visit/', register_visit, name='visit'),
    path('visitone/<int:pk>', ONE_visit, name='visit_one'),
    path('cancel/<int:pk>', cancel, name='cancel'),
    path('visitregi/<int:pk>/<int:pi>', visit_register, name='visit_register'),
    path('systemrec/', e_systemREC, name='e_systemREC'),
    path('systemskier/', e_systemSKIER, name='e_systemSKIER'),
    path('organization/', organizations, name='organization'),
    path('organization/spec', spec , name='spec'),
    path('organization/hospital', hospital , name='hospital'),
    path('organization/clinic', clinic , name='clinic'),
    path('organization/page/<int:id>', organizations_page, name='organization_page'),
    path('organization/<int:id>', organizations_next, name='organization_next'),
    # path('registervisit/', register_visit, name='register_visit'),
    path('visitreg/<int:unitpk>/<int:perspk>', visitreg, name='visitreg'),
    path('dekl', DEKL_ON, name='dekl'),


    path('api-auth/', include('rest_framework.urls')),


    # url(r'^test/$', views.test.as_view(), name='test-list'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Pacjent/models.py
from django.db import models
from django.contrib.auth.models import *
from Placowki.models import *
from Profile.models import *
from Terminarz.models import *
from Slowniki.models import *
# Create your models here.


class Document(models.Model):
    name = models.CharField("Nazwa", max_length=100, null=True, unique=True)
    author_user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, verbose_name="Użytkownik")
    author_person = models.ForeignKey(Personal, on_delete=models.PROTECT, null=True, verbose_name="Pacjent")
    doc = models.FileField("Załącznik", null=True, blank=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Dokumenty"

class Visit(models.Model):
    STATUS = (
        ('0', ('Niepotwierdzony')),
        ('1', ('Potwierdzony')),

    )
    STATUS_AC = (
        ('0', ('Zarejestrowana')),
        ('1', ('Zapalnowana')),
        ('2', ('Do realizacji')),
        ('3', ('Zrealizowana')),
        ('4', ('Odwołana')),

    )
    VISIT_TYPE = (
        ('0', ('Receptowa')),
        ('1', ('Porada')),
        ('2', ('Teleporada')),
        ('3', ('Z skierowaniem')),
        ('4', ('Kontynuacja')),
        ('5', ('')),


    )
    patient_user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    patient_person = models.ForeignKey(Personal, on_delete=models.PROTECT, null=True)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, null=True, verbose_name="Komórka Organizacyjna")
    struct = models.ForeignKey(Struct_Organization, on_delete=models.PROTECT, null=True, verbose_name="Zakład leczniczy")
    unity = models.ForeignKey(Unit, on_delete=models.PROTECT, null=True, verbose_name="Jednostka ")
    term = models.ForeignKey(Term_day, on_delete=models.CASCADE, unique=True, null=True, verbose_name="Data Wizyty ")
    key = models.CharField("Kod e-skierowania", max_length=4, null=True)
    id10 = models.ManyToManyField(ICD10, verbose_name="Rozpoznania", null=True)
    description = models.TextField("Opis", null=True)
    description_person = models.TextField("Opis lekarza", null=True)
    status = models.CharField("Status aktualny", max_length=100, null=True, choices=STATUS_AC, default='0')
    confirmation = models.CharField("Potwierdzenie wizyty", max_length=100,
                                    choices=STATUS, default='0', null=True)
    type_visit = models.CharField("Rodzajy Wizyty", max_length=100,
                                    choices=VISIT_TYPE, default='5')
    dateregister = models.DateField(default=timezone.now)




    class Meta:
        verbose_name_plural = "Wizyty"

class e_system_SKIEROWANIA(models.Model):
    key_e = models.CharField("Kod skierowania", max_length=4, null=True, blank=True, unique=True)
    idvisit = models.ForeignKey(Visit, on_delete=models.PROTECT, verbose_name="Wizyta")
    idpac = models.ForeignKey(Personal, on_delete=models.PROTECT, verbose_name="Pacjents")
    iddoc = models.ForeignKey(Personal_med, on_delete=models.PROTECT, verbose_name="Lekarz")

    def __str__(self):
        return (self.key_e)

    class Meta:
        verbose_name_plural = "Skierowania"
class e_system_RECEPTY(models.Model):
    key_e = models.CharField("Kod Recepty", max_length=4, null=True, blank=True, unique=True)
    idvisit = models.ForeignKey(Visit, on_delete=models.PROTECT, verbose_name="Wizyta")
    idpac = models.ForeignKey(Personal, on_delete=models.PROTECT, verbose_name="Pacjents")
    iddoc = models.ForeignKey(Personal_med, on_delete=models.PROTECT, verbose_name="Lekarz")

    def __str__(self):
        return (self.key_e)

    class Meta:
        verbose_name_plural = "Recepty"

class Form_all(models.Model):

     name = models.CharField("Nazwa Formularza do pobrania", max_length=100, null=True, blank=True)
     file = models.FileField("Fromularz do pobrania", null=True, blank=True)

     def __str__(self):
         return (self.name)
     class Meta:
         verbose_name_plural = "Formularze"


class Form_user(models.Model):

    FORM_TYPE = (
        ('0', ('Deklaracja do Lekarza')),
        ('1', ('Deklaracja do Pielęgniarki środowiskowej')),
        ('2', ('Deklaracja do Położnej')),
        ('3', ('Formularz zdrowotny COVID')),
    )
    STAUS = (
        ('0', ('Przesłany')),
        ('1', ('W trakcie weryfikacji')),
        ('2', ('Zakceptowany')),
        ('3', ('Niezakceptowany')),

    )
    name = models.CharField("Nazwa przesłanego Formularza ", max_length=100, null=True, blank=True)
    patient_person = models.ForeignKey(Personal, on_delete=models.PROTECT, null=True, verbose_name="Pacjent")
    # medical = models.ForeignKey(Personal_med, on_delete=models.PROTECT, null=True, verbose_name="Personel")
    type_forms = models.CharField("Rodzaj Formularza", max_length=100, null=True, choices=FORM_TYPE)
    status = models.CharField("Status dokumentu", max_length=100, null=True, choices=STAUS, default=0)
    remarks_user = models.TextField("Uwagi użytkownika", null=True)
    remarks_person = models.TextField("Uwagi Pracownika placówki", null=True)
    name_unit = models.ForeignKey(Unit, on_delete=models.PROTECT, verbose_name="Jednostka", null=True)
    publish_date = models.DateField("Data przesłania", default=timezone.now)
    file = models.FileField("Fromularz do pobrania", null=True, blank=True)

    def __str__(self):
        return (self.name)
    class Meta:
        verbose_name_plural = "Formularze przesłane przez użytkownika"
class dekl(models.Model):

    idpac = models.ForeignKey(Personal, on_delete=models.CASCADE, unique=True, null=True, verbose_name="Pacjent")
    iddoc = models.ForeignKey(Personal_med, on_delete=models.CASCADE, unique=True, null=True, verbose_name="Lekarz")
    idunit = models.ForeignKey(Unit, on_delete=models.CASCADE, verbose_name="Jednostka")
    idfield = models.ForeignKey(Form_user, on_delete=models.CASCADE, unique=True, null=True, verbose_name="Formularz")

    class Meta:
        verbose_name_plural = "Deklaracje"

Terminarz/models.py
from django.db import models
from Placowki.models import *
from Profile.models import *
from django.utils import timezone, dateformat
# Create your models here.
class Term(models.Model):
    WORK = (
        ('0', ('Lekarz')),
        ('1', ('Pielęgniarka')),
        ('2', ('Położna')),
    )
    DAY = (
        (0, ('Poniedziałek')),
        (1, ('Wtorek')),
        (2, ('Środa')),
        (3, ('Czwartek')),
        (4, ('Piątek')),
        (5, ('Sobota')),
        (6, ('Niedziela')),
    )

    work_place = models.ForeignKey(Unit, on_delete=models.PROTECT, null=True, verbose_name="Jednostka")
    work_person = models.ForeignKey(Personal_med, on_delete=models.PROTECT, null=True, verbose_name="Osoba personelu")
    work_type = models.CharField("Typ terminarza", max_length=100, choices=WORK, null=True)
    work_start = models.TimeField(auto_now=False, auto_now_add=False, verbose_name="Początek wizyty")
    work_stop = models.TimeField(auto_now=False, auto_now_add=False, verbose_name="Koniec wizyty")
    work_day = models.IntegerField("Dzień tygodnia", null=True, choices=DAY)
    work_time = models.IntegerField("Czas trwania wizyty", null=True)
    work_start_date = models.DateField("Data początku",null=True)
    work_stop_date = models.DateField("Data początku",null=True)
    work_date = models.DateField("Data generacji", default=timezone.now , null=True)
    class Meta:
        verbose_name_plural = "Harmonogram"

class Term_day(models.Model):
    DAY = (
        ('0', ('Poniedziałek')),
        ('1', ('Wtorek')),
        ('2', ('Środa')),
        ('3', ('Czwartek')),
        ('4', ('Piątek')),
        ('5', ('Sobota')),
        ('6', ('Niedziela')),
    )
    work_place = models.ForeignKey(Unit, on_delete=models.PROTECT, null=True, verbose_name="Jednostka")
    work_person = models.ForeignKey(Personal_med, on_delete=models.PROTECT, null=True, verbose_name="Osoba personelu")
    work_date = models.DateField("Data", null=True)
    work_time = models.TimeField(auto_now=False, auto_now_add=False, verbose_name="Godzina wizyty")
    work_day = models.CharField("Dzień tygodnia", max_length=100, null=True, choices=DAY)
    work_type = models.CharField("Typ terminarza", max_length=100, null=True)


    def __str__(self):

        text_date = self.work_date.strftime("%m/%d/%Y")
        text_time = self.work_time.strftime("%H:%M:%S")
        return (text_date +' '+ text_time)

    class Meta:
        verbose_name_plural = "Terminarz"

templates/Customer/Visit.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% block navbar %}


                <div class="nav_list"> <a href="#" class="nav_link "> <i class='bx bx-grid-alt nav_icon'></i> <span class="nav_name">Strona Główna</span> </a>
                    <a href="{% url 'organization' %}" class="nav_link"> <i class='bx bx-plus-medical nav_icon'></i> <span class="nav_name">Zarejestruj wizytę</span> </a>
                    <a href="{% url 'e_systemREC' %}" class="nav_link"> <i class='bx bx-capsule nav_icon'></i> <span class="nav_name">Recepty</span> </a>
                    <a href="{% url 'e_systemSKIER' %}" class="nav_link"> <i class='bx bx-donate-heart nav_icon'></i> <span class="nav_name">Skierowania</span> </a>
                    <a href="{% url 'visit' %}" class="nav_link active "> <i class='bx bx-bookmark nav_icon'></i> <span class="nav_name">Przegląd wizyt</span> </a>
                    <a href="{% url 'upload' %}" class="nav_link"> <i class='bx bx-folder nav_icon'></i> <span class="nav_name">Dokumenty</span> </a>
                    <a href="{% url 'editprofile' %}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Profil</span> </a>
                    </div>
{% endblock navbar %}
{% block content %}
    <h3></h3>
 <div class="container">

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    </div>
     </br>
    </br>
    </br>

    <h1 style="text-align: center"> Twoje Wizyty</h1>
{% for message in messages %}
                <h3 id="message">{{ message }}</h3>

            {% endfor %}
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="table-responsive">
                    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 50.641px;">#</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 160.312px;">Jednostka</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 160.312px;">Lekarz</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Data rejestracji</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Data wizyty</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Rodzaj</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Status</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>



                                         {% for i in show %}

                                            <tr role="row" class="odd">
{#                                                <td><div class="d-grid gap-2">    <a type="button" href="{% url 'visit_register' pk=i.work_place.id pi=i.id %}" class="btn btn-outline-success"  >Zarejestruj</a></div></td>#}
                                                <td class="sorting_1">{{forloop.counter }}</td>

                                                <td>{{ i.unity}}</td>
                                                <td><b>{{ i.term.work_person.first_name}} {{ i.term.work_person.first_name}}</b>  {{ i.term.work_person.npwz}}</td>
                                                <td><b>{{ i.dateregister}}</b> </td>
                                                <td><b>{{ i.term.work_date}} <b>{{ i.term.work_time }}</b></td>
                                                <td>{{ i.get_type_visit_display}} </td>
                                                <td>{{ i.get_confirmation_display}} </td>
                                                <td><a href="{% url 'visit_one' pk=i.id %}"  class="btn btn-secondary">PRZEJDZ DO WIZYTY</a></td>
                                            </tr>








                                               {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>












{% endblock content %}
{% block extrascripts %}

    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>

    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}

templates/Customer/Visit_register.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap %}
 {% block style %}

 {% endblock %}

{% block navbar %}


                <div class="nav_list"> <a href="#" class="nav_link "> <i class='bx bx-grid-alt nav_icon'></i> <span class="nav_name">Strona Główna</span> </a>
                    <a href="{% url 'organization' %}" class="nav_link active"> <i class='bx bx-plus-medical nav_icon'></i> <span class="nav_name">Zarejestruj wizytę</span> </a>
                    <a href="{% url 'e_systemREC' %}" class="nav_link "> <i class='bx bx-capsule nav_icon'></i> <span class="nav_name">Recepty</span> </a>
                    <a href="{% url 'e_systemSKIER' %}" class="nav_link"> <i class='bx bx-donate-heart nav_icon'></i> <span class="nav_name">Skierowania</span> </a>
                    <a href="{% url 'visit' %}" class="nav_link  "> <i class='bx bx-bookmark nav_icon'></i> <span class="nav_name">Przegląd wizyt</span> </a>
                    <a href="{% url 'upload' %}" class="nav_link"> <i class='bx bx-folder nav_icon'></i> <span class="nav_name">Dokumenty</span> </a>
                    <a href="{% url 'editprofile' %}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Profil</span> </a>
                    </div>
{% endblock navbar %}


{% block content %}


    <h1 style="text-align: center"><i class='bx bxs-analyse bx-spin' style='color:#4723d9' ></i> Rejestrujesz wizytę na termin {{ term.get_work_day_display }} {{ term.work_date }} na godzinę {{ term.work_time }}  </h1>
{% for message in messages %}
                <h3 id="message">{{ message }}</h3>
{% endfor %}
<form method="post">
{% csrf_token %}
            <fieldset disabled>
                <div class="form-group">
                    <div class="row">
                         <div class="col">
                             <label>{{ forms.patient_user.label }}</label>
                             {{ forms.patient_user }}
                        </div>
                    <div class="col">
                  <label>{{ forms.patient_person.label }}</label>
                      {{ forms.patient_person}}
                    </div>
                </div>
            </div>
{#-------------------------------------------------------------------------------#}


                <div class="form-group">
                <div class="row">

                      <div class="col">
                             <label>{{ forms.organization.label }}</label>
                             {{ forms.organization }}
                        </div>
                          <div class="col">
                             <label>{{ forms.struct.label }}</label>
                             {{ forms.struct }}
                        </div>

                         <div class="col">
                        <label>{{ forms.unity.label }}</label>
                            {{ forms.unity }}
                        </div>

                </div>
            </div>
</fieldset>
            <fieldset style="display: none">
                <div class="form-group">
                    <div class="row">
                         <div class="col">
                             <label>{{ forms.patient_user.label }}</label>
                             {{ forms.patient_user }}
                        </div>
                    <div class="col">
                  <label>{{ forms.patient_person.label }}</label>
                      {{ forms.patient_person}}
                    </div>
                </div>
            </div>
{#-------------------------------------------------------------------------------#}


                <div class="form-group">
                <div class="row">

                      <div class="col">
                             <label>{{ forms.organization.label }}</label>
                             {{ forms.organization }}
                        </div>
                          <div class="col">
                             <label>{{ forms.struct.label }}</label>
                             {{ forms.struct }}
                        </div>

                         <div class="col">
                        <label>{{ forms.unity.label }}</label>
                            {{ forms.unity }}
                        </div>

                </div>
            </div>
</fieldset>
    <div class="form-group">
                    <div class="row">
                         <div class="col">
                             <label>{{ forms.key.label }}</label>
                             {{ forms.key }}
                        </div>

                </div>
            </div>

<div class="form-group">
                    <div class="row">
                         <div class="col">
                             <label>{{ forms.description.label }}</label>
                             {{ forms.description }}
                        </div>

                </div>
            </div>


<div class="d-grid gap-2">    <input type="submit" class="btn btn-outline-success" value="Zarejestruj"></div>

</form>

{% endblock content %}
{% block extrascripts %}

    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>

    <script type="text/javascript">$('#sampleTable').DataTable();</script>

{% endblock extrascripts %}